# Generated by Django 3.2.8 on 2021-11-05 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsModel',
        ),
        migrations.DeleteModel(
            name='LikesModel',
        ),
        migrations.DeleteModel(
            name='PostsModel',
        ),
    ]
