# Generated by Django 3.2.8 on 2021-11-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myusers', '0001_initial'),
        ('main', '0002_auto_20211105_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMediaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(max_length=128, unique=True, verbose_name='Тип медиа')),
            ],
            options={
                'verbose_name': 'Тип медиа файла',
                'verbose_name_plural': 'Типы медиа файлов',
                'db_table': 'TypeMedia',
            },
        ),
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст поста')),
                ('media', models.FileField(blank=True, upload_to='media_post', verbose_name='Медиа файл')),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myusers.usersmodel', verbose_name='Хозяин поста')),
                ('type_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.typemediamodel', verbose_name='Тип медиа файла')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='LikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.postsmodel', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myusers.usersmodel', verbose_name='Пользователя')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'db_table': 'Likes',
            },
        ),
        migrations.CreateModel(
            name='FollowersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='myusers.usersmodel', verbose_name='Пользователь')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myusers.usersmodel', verbose_name='Подписчик')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'db_table': 'Followers',
            },
        ),
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.postsmodel', verbose_name='Пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myusers.usersmodel', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
                'db_table': 'Comments',
            },
        ),
    ]
